/** 规范 Conversation Command API 的传输与后台派发常量。 */
export const CONVERSATION_COMMAND_SCHEMA_VERSION = 1 as const
export const CONVERSATION_COMMAND_IDEMPOTENCY_KEY_MAX_LENGTH = 200
export const CONVERSATION_OUTBOX_DEFAULT_BATCH_SIZE = 25
export const CONVERSATION_OUTBOX_MAX_ATTEMPTS = 8
export const CONVERSATION_POLL_AFTER_MS = 1_000
