import type { Scenario } from "./landing-demo"

/** 英文首页的静态演示；不调用模型、不创建真实会话。与中文场景保持相同 ID。 */
export const englishScenarios: Scenario[] = [
  { id: "prd", category: "Write a PRD", title: "Design branching in ThreadChat", description: "From the user flow to context rules and the edge cases that are easy to miss.", takeaway: "Clarify the requirement—and its boundaries.", lanes: [
    { title: "Branching PRD", question: "Design branching in ThreadChat, including the user flow, rules, and acceptance criteria.", text: "When a user wants to explore a sentence without interrupting the original discussion, they can create a branch from it. The first version focuses on selecting, asking, and continuing the discussion.", heading: "Core user flow", bullets: ["Select a sentence in a reply.", "Choose ‘Ask here’ and enter a follow-up question.", "Continue in the adjacent branch while the main thread stays unchanged."], anchor: "A branch should inherit the context at creation time, so users do not have to explain it again.", note: "Still to clarify: what gets inherited, what happens after an edit, and how the source is shown." },
    { title: "What does a branch inherit?", question: "Which context should a new branch inherit?", text: "Include the existing background at the moment of branching, plus the selected discussion focus. Together, these help the model understand the new question. Later messages in the branch do not automatically flow back into the main thread.", heading: "Three kinds of context", rows: [["Background", "A frozen snapshot of the preceding discussion"], ["Focus", "The sentence currently selected"], ["New content", "Messages added only within the branch"]], anchor: "The branch inherits a creation-time snapshot, not a continuously synchronized main thread." },
    { title: "After the main thread is edited", question: "Should an existing branch change when the main thread is edited later?", text: "Do not silently rewrite the background of an existing branch. Preserve its creation-time snapshot so its questions and answers retain a clear origin. Changes at the source can be surfaced to the user.", heading: "Acceptance checks", rows: [["Edit the main thread", "Existing branch context stays unchanged"], ["Ask a follow-up", "Continue using the branch’s original background"], ["Inspect the source", "The branch’s origin is identifiable"]] },
  ] },
  { id: "technical", category: "Technical design", title: "Bring branch conclusions back to the main thread", description: "Explore the details, then explicitly reference the useful conclusions with @Artifact.", takeaway: "Explore deeply, then bring back what you need.", artifact: true, lanes: [
    { title: "Bring conclusions back", question: "How can a conclusion from a branch be used in the main thread?", text: "Keep branches independent so every detail does not automatically flood the main thread. When a user decides that a conclusion is useful, they can bring it back explicitly and continue the original task.", heading: "Design constraints", bullets: ["Keep branch context independent.", "Let the user choose which conclusions to use.", "Preserve the link to the source."], anchor: "Turn the conclusion into an Artifact and explicitly reference it with @ in the main thread." },
    { title: "Design @Artifact references", question: "How should turning a conclusion into an Artifact and referencing it with @ work?", text: "The user types @ in the composer and selects an accessible Artifact. A non-editable reference chip appears; the user can continue typing their question around it.", heading: "A complete reference flow", rows: [["Type @", "Show available Artifacts"], ["Select an Artifact", "Insert a non-editable reference chip"], ["Continue asking", "Send the question with the chosen conclusion"]], anchor: "If the content is already in context, referencing it should not inject it a second time." },
    { title: "Avoid duplicate context", question: "Should a reference carry the full content or just an identifier? Must content already in context be sent again?", text: "First check whether the content is already present in this generation’s context. If it is, retain a stable reference marker. Otherwise, load the necessary content according to the server’s reference rules.", heading: "Draft conclusion", rows: [["Content already present", "ID, title, and stable reference marker"], ["First inclusion", "Load the necessary authorized content"], ["Permission check", "Verify access on the server"]], note: "Save this conclusion as an Artifact, then reference it in the main thread." },
  ] },
  { id: "marketing", category: "Marketing plan", title: "Find ThreadChat’s first users", description: "Follow a launch plan into the reasons to try it, then turn those reasons into a visible demonstration.", takeaway: "Turn a product claim into a reason you can test.", lanes: [
    { title: "First-month acquisition plan", question: "Create a first-month acquisition plan for ThreadChat. We want users to try it with real tasks.", text: "Recruit around one specific workflow first. Observe whether users make progress on their tasks before broadening distribution. Start with PRDs and technical designs.", heading: "Three tasks for the first month", bullets: ["Record a complete branching discussion.", "Invite people who have a current task.", "Follow up to see whether they return with a second task."], anchor: "Users already use AI. Why would they need ThreadChat too?" },
    { title: "Why try another AI product?", question: "Users already use AI. Why would they need ThreadChat too?", text: "Test a concrete hypothesis: during complex work, users need to keep the original task in view while exploring details. Branches give each question its own discussion space and reduce repeated explanations in separate chats.", heading: "Test before making claims", rows: [["User hypothesis", "Details frequently pull users away from their task"], ["Product mechanism", "Branch from a sentence with its background"], ["Validation signal", "The user returns with a second real task"]], anchor: "Show a real interaction: explore the details while the main task stays in view." },
    { title: "Show the value in 30 seconds", question: "How can a 30-second demo make that value clear?", text: "Choose a natural question in a PRD. Show the main task, select a rule, ask about its edge cases, and end with three columns so viewers can see how the questions connect.", heading: "Storyboard", rows: [["0–6 seconds", "A concrete requirement and an unresolved rule"], ["6–20 seconds", "Select the rule and ask a follow-up"], ["20–30 seconds", "Show three columns and the acceptance boundaries"]] },
  ] },
  { id: "research", category: "Deep research", title: "Compare WorkBuddy with alternatives", description: "Follow a product claim into its capabilities, evidence, and differences that still need testing.", takeaway: "See a claim? Ask what supports it.", notice: "Demo source snapshot: September 10, 2026", sources: [{ label: "Tencent’s introduction", url: "https://www.linkedin.com/posts/tencent-cloud_tencent-workbuddy-an-ai-native-agent-designed-activity-7465630719772467200-s9_z" }, { label: "Claude Cowork", url: "https://claude.com/product/cowork" }], lanes: [
    { title: "WorkBuddy comparison", question: "Analyze WorkBuddy’s audience, core capabilities, and differences from similar products.", text: "Tencent describes WorkBuddy as a product for daily office tasks, emphasizing planning and executing multi-step work from natural-language instructions. Claude Cowork provides a comparable task-execution product to investigate.", heading: "Use a consistent comparison", rows: [["WorkBuddy", "Official materials emphasize planning and executing office tasks"], ["Claude Cowork", "Official materials emphasize work across files and tools"], ["Still to test", "Success rates and human intervention on identical tasks"]], anchor: "Compare not just answer quality, but how the task is actually executed." },
    { title: "How is this different from chat?", question: "What is the main difference from an ordinary AI chat tool?", text: "Their official descriptions emphasize operating on files and tools and delivering work for review. However, general chat products may also use tools, so ‘chat versus execution’ is not a sufficient distinction.", heading: "Observe these stages", rows: [["Input", "Required files, background, and permissions"], ["Execution", "Which steps tools actually perform"], ["Delivery", "Whether the result is usable or needs rework"]], anchor: "Official feature descriptions provide clues, but do not replace real task tests." },
    { title: "Separate evidence from promotion", question: "Which actual features support this distinction, and which claims still need verification?", text: "Label website statements as official descriptions and task execution records as test evidence. These introductions alone do not establish which product is more reliable. Compare them with the same materials and acceptance criteria next.", heading: "Evidence checklist", rows: [["Task", "The same source-review and report-writing task"], ["Record", "Completion, failed steps, and human intervention"], ["Conclusion", "Do not rank reliability before testing"]] },
  ] },
  { id: "ai", category: "Learn a topic", title: "Learn AI from scratch", description: "Branch into unfamiliar concepts, then return to your learning path when they make sense.", takeaway: "Understand the concept, then return to the bigger picture.", lanes: [
    { title: "My AI learning path", question: "How can a beginner learn AI? Help me build a learning path.", text: "Start by using AI for a real question, learn the basic concepts, and then try a small project. You do not need to memorize every term immediately; explore unfamiliar ones as they appear.", heading: "A gradual learning path", bullets: ["Learn what language models can and cannot do.", "Understand tokens, context, and prompts.", "Explore RAG, embeddings, and agents.", "Build a small project and inspect both results and failures."], anchor: "Understand language models before moving into more complex applications." },
    { title: "What is a language model?", question: "How does a language model understand and generate text?", text: "An introductory view: the model converts input into tokens, uses patterns learned during training to process the context, and predicts subsequent tokens. Complex abilities can emerge, but fluent text is not necessarily correct.", heading: "Separate three concepts", rows: [["Training", "Learning patterns from many examples"], ["Context", "Information supplied in this particular input"], ["Generation", "Producing output step by step from context"]], anchor: "The model processes tokens, which are not always equivalent to a word or a character." },
    { title: "Is a token a word?", question: "How is a token different from a word or a character?", text: "A token is a unit used by a tokenizer. It may represent a character, part of a word, or a common character sequence. Different models can split the same text differently.", heading: "Avoid a fixed conversion ratio", rows: [["Text", "What people read and write"], ["Token", "A processing unit for model input and output"], ["Length", "Count using the tokenizer for the actual model"]], note: "Now return to the main thread to continue learning about RAG and agents." },
  ] },
  { id: "stocks", category: "Learn a topic", title: "Understand a public company from scratch", description: "Follow a learning path into financial concepts and a common point of confusion.", takeaway: "Understanding a company starts with clarifying a concept.", notice: "An educational example about financial statements and business operations", lanes: [
    { title: "How to understand a company", question: "How can a beginner learn to understand a public company?", text: "Start with how the business makes money and who its customers are, then read the financial statements and learn about risk and valuation. Keep facts, explanations, and your own judgments separate.", heading: "Build a reading framework", bullets: ["Business: products, customers, and competition.", "Financials: balance sheet, income statement, and cash flow statement.", "Risk: debt, customer concentration, and operating changes."], anchor: "When reading financial statements, distinguish profit from cash flow." },
    { title: "Profit versus cash flow", question: "What is the difference between profit and cash flow?", text: "Profit reflects recognized revenue minus expenses under accounting rules. Cash flow tracks actual cash coming in and going out. Revenue recognition and cash collection do not always happen at the same time.", heading: "Two different questions", rows: [["Profit", "How much was earned under accounting rules"], ["Cash flow", "How cash actually changed during the period"], ["Analysis", "Read the statements alongside the business explanation"]], anchor: "A company can report a profit and still be short of cash." },
    { title: "Profitable but short of cash?", question: "Why can a profitable company still lack enough cash?", text: "Sales may have been recognized before customers pay. Cash may also be used for inventory, equipment, or debt repayment. Distinguish operating, investing, and financing cash flow rather than judging a company from one measure alone.", heading: "Where to look next", rows: [["Receivables", "Timing differences between revenue and collection"], ["Inventory and purchases", "Cash tied up in operations"], ["Investment and debt", "Cash spent on investment and repayment"]], note: "Consider profit and cash flow together, then return to learning about the company’s business." },
  ] },
]
