'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {AtSign,ArrowUp,GitBranch,MessageSquareReply,ChevronDown,ChevronRight,FileText,X,Check,Copy,CornerDownLeft} from 'lucide-react';
import {Popover} from '@base-ui/react/popover';
import {DemoPopoverContent} from './demo-popover-content';
import {Command,CommandList,CommandItem} from '@/components/ui/command';
import type {Scenario} from '@/constants/landing-demo';
import type {DemoView} from './use-demo-sequence';
type Props={scenario:Scenario;index:number;view:DemoView;interact:(p:Partial<DemoView>)=>void;onFork:(i:number)=>void;boundary:HTMLElement|null};
export function ThreadPane({scenario:s,index:i,view:v,interact,onFork,boundary}:Props){
 const lane=s.lanes[i],list=useRef<HTMLDivElement>(null),[draft,setDraft]=useState(''),[folded,setFolded]=useState(false),[copied,setCopied]=useState(false),[localReply,setLocalReply]=useState(false);
 const anchorRef=useRef<HTMLButtonElement>(null), composerRef=useRef<HTMLDivElement>(null);
 const [artifactExpanded,setArtifactExpanded]=useState(false);
 const accent=i===2?'#7c62a8':'#2f7d6b';
 const selected=v.source===i&&v.overlay!=='none';
 const input=i===0?v.mainDraft:draft;
 useEffect(()=>{if(i===0&&v.returned)list.current?.scrollTo({top:list.current.scrollHeight,behavior:'smooth'})},[v.returned,i]);
 const submit=()=>{if(!input.trim()&&!(i===0&&v.referenceSelected))return;if(i===0&&v.referenceSelected){interact({returned:true,mainDraft:'',mentionOpen:false})}else{setLocalReply(true);setDraft('');interact({mainDraft:i===0?'':v.mainDraft})}};
 const copy=async()=>{try{await navigator.clipboard.writeText([lane.text,lane.heading,...lane.bullets??[],...lane.rows?.map(r=>r.join('：'))??[],lane.anchor??''].join('\n'));setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}};
 if(folded)return <button className="col-strip" style={{'--tc-accent':accent} as CSSProperties} onClick={()=>setFolded(false)} aria-label={`展开${lane.title}`}><ChevronRight size={16}/><span className="depth-badge">L{i}</span><span className="vt">{lane.title}</span></button>;
 return <article className={`column ${i?'branch':''}`} style={{'--tc-accent':accent} as CSSProperties} aria-label={`${i?'分支 '+i:'主线'}：${lane.title}`}>
 <header className="col-head">{i>0&&<div className="crumb"><span>主线</span><ChevronRight size={10}/>{i===2&&<><span>{s.lanes[1].title}</span><ChevronRight size={10}/></>}<span className="here">{lane.title}</span></div>}<div className="ctitle-row"><span className={i?'depth-badge':'anchor-tag'}>{i?`L${i}`:'锚定'}</span><strong className="ctitle">{i?lane.title:'主线'}</strong>{i>0&&<button className="cbtn" onClick={()=>setFolded(true)}>收起</button>}</div>{!i&&<div className="col-sub">{lane.title}</div>}</header>
 {i>0&&<div className="context-fixed"><div className="focus-banner"><span className="fn">{i}</span><div className="ft"><span className="lbl">讨论焦点 · 划选自「{s.lanes[i-1].title}」</span><q>{s.lanes[i-1].anchor}</q></div></div><details className="inherited" open={v.inherited===i}><summary data-cursor-target={`inherited-${i}`} onClick={e=>{e.preventDefault();interact({inherited:v.inherited===i?-1:i})}}>{v.inherited===i?'▾':'▸'} 继承的上文 · {i*2} 条</summary><div className="inherited-body">{s.lanes.slice(0,i).map(l=><div key={l.title}><p>你：{l.question}</p><p>AI：{l.text}</p></div>)}</div></details></div>}
 <div className="message-list" ref={list}><div className="lane"><div className="user-message">{lane.question}</div><div className="assistant-message"><p>{v.texts[i]}{!v.ready[i]&&<span className="stream-caret"/>}</p>{v.ready[i]&&<><h3>{lane.heading}</h3>{lane.bullets&&<ol>{lane.bullets.map(b=><li key={b}>{b}</li>)}</ol>}{lane.rows&&<div className="table-scroll"><table><thead><tr><th>{i===2?'检查项':'关注点'}</th><th>说明</th></tr></thead><tbody>{lane.rows.map(([a,b])=><tr key={a}><td>{a}</td><td>{b}</td></tr>)}</tbody></table></div>}
 {lane.anchor&&<Popover.Root open={selected} onOpenChange={open=>{if(!open&&selected)interact({overlay:'none'})}}><div className="anchor-wrap"><button ref={anchorRef} className="source-anchor" style={{'--selection-width':selected?'100%':'0%'} as CSSProperties} data-cursor-target={`anchor-${i}`} onClick={()=>interact({overlay:'toolbar',source:i})}>{lane.anchor}</button>{v.visible>i+1&&<button className="footnote" aria-label={`查看分支 ${i+1}`} onClick={()=>document.getElementById(`thread-lane-${i+1}`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'nearest'})}>{i+1}</button>}</div><DemoPopoverContent anchor={anchorRef} boundary={boundary} className={`landing-demo-popover ${v.overlay==='question'?'question-surface':'toolbar-surface'}`} side="bottom" align="center" sideOffset={9}>
 {v.overlay==='toolbar'?<><button onClick={()=>{interact({overlay:'none',mainDraft:i===0?`关于「${lane.anchor}」，`:v.mainDraft});if(i)setDraft(`关于「${lane.anchor}」，`)}}><MessageSquareReply size={17}/>在当前对话问</button><button data-cursor-target="fork-open" onClick={()=>interact({overlay:'question',popupQuestion:s.lanes[i+1].question})}><GitBranch size={17}/>此处提问</button></>:<><div className="lbl">从这句话开启分支<button aria-label="关闭提问" onClick={()=>interact({overlay:'none'})}><X size={15}/></button></div><div className="quote">{lane.anchor}</div><textarea aria-label="分支问题" value={v.popupQuestion} onChange={e=>interact({popupQuestion:e.target.value})}/><button className="fork-submit" data-cursor-target="fork-submit" disabled={!v.popupQuestion.trim()} onClick={()=>onFork(i)}><GitBranch size={15}/>在右侧创建分支</button><div className="placement-preview"><small>自动带上已有背景，无需重新解释</small></div></>}
 </DemoPopoverContent></Popover.Root>}
 {lane.note&&<p className="lane-note">{lane.note}</p>}
 {s.artifact&&i===2&&<div className="artifact-block">{!v.artifactReady?<button className="create-artifact" data-cursor-target="artifact-create" onClick={()=>interact({artifactReady:true})}><FileText size={16}/>整理为 Artifact</button>:<><button className="artifact-card" data-cursor-target="artifact-create" onClick={()=>setArtifactExpanded(e=>!e)} aria-expanded={artifactExpanded}><span className="artifact-icon"><FileText size={21}/></span><span><strong>分支结论引用方案</strong><small>Artifact · 来自此分支</small></span><ChevronDown size={15}/></button>{artifactExpanded&&<div className="artifact-content">主动引用、保留来源、避免重复注入。服务端校验权限，引用胶囊支持移除。</div>}<p className="artifact-hint">回到主线，输入 @ 引用这份结论。</p></>}</div>}
 <div className="message-actions"><button aria-label="复制回复" onClick={copy}>{copied?<Check size={14}/>:<Copy size={14}/>}</button><span>{copied?'已复制':''}</span></div></>}
 </div>
 {v.returned&&i===0&&<div className="returned-block"><div className="user-message"><span className="reference-inline"><AtSign size={13}/>分支结论引用方案</span>根据这份结论，补充主线的实现步骤和验收标准。</div><div className="assistant-message"><p>已结合你主动引用的分支结论，将方案收敛为三步：</p><ol><li>输入 @，检索有权限访问的 Artifact。</li><li>选中后插入引用胶囊，并保留来源。</li><li>发送时校验权限，按上下文去重。</li></ol><h3>验收标准</h3><p>引用可移除、来源可追溯；未引用的分支细节不进入主线。</p></div></div>}
 {localReply&&<div className="local-reply" role="status">当前体验支持示例中的问题。点击划线的原句继续追问，或切换一个感兴趣的场景。</div>}
 </div></div>
 <div className="composer"><Popover.Root open={i===0&&v.mentionOpen} onOpenChange={open=>{if(i===0&&!open)interact({mentionOpen:false})}}><div ref={composerRef} className="composer-inner">
 {i===0&&v.referenceSelected&&!v.returned&&<span className="reference-capsule" contentEditable={false}><FileText size={13}/>分支结论引用方案<button aria-label="移除引用" onClick={()=>interact({referenceSelected:false})}><X size={12}/></button></span>}
 <textarea data-cursor-target={i===0?'main-input':`input-${i}`} aria-label={i===0?'在主线继续提问':`在分支 ${i} 继续提问`} placeholder={i===0?(v.artifactReady?'输入 @ 引用分支结论…':'继续在主线提问…'):'在这个分支里追问…'} value={input}
 onChange={e=>{const value=e.target.value;if(i===0)interact({mainDraft:value,mentionOpen:!!s.artifact&&v.artifactReady&&value.endsWith('@')});else{setDraft(value);interact({})}}}
 onKeyDown={e=>{if(e.nativeEvent.isComposing)return;if(i===0&&v.mentionOpen&&e.key==='Enter'){e.preventDefault();interact({referenceSelected:true,mentionOpen:false,mainDraft:v.mainDraft.replace(/@$/,'')});return}if(e.key==='Escape'&&v.mentionOpen){e.preventDefault();interact({mentionOpen:false});return}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}}/>
 <div className="composer-toolbar"><span className="composer-options">Claude Opus 4.6 <ChevronDown size={11}/></span><button className="send-button" data-cursor-target={i===0?'main-send':`send-${i}`} aria-label="发送问题" disabled={!input.trim()&&!(i===0&&v.referenceSelected)} onClick={submit}><ArrowUp size={15}/></button></div>
 </div><DemoPopoverContent anchor={composerRef} boundary={boundary} className="landing-demo-popover mention-surface" side="top" align="start"><Command><div className="mention-label">引用分支产物 · 按 Enter 选择</div><CommandList><CommandItem value="分支结论引用方案" data-cursor-target="artifact-option" onSelect={()=>interact({referenceSelected:true,mentionOpen:false,mainDraft:v.mainDraft.replace(/@$/,'')})}><FileText size={17}/><span>分支结论引用方案<small>来自「避免重复传递内容」</small></span><CornerDownLeft size={13}/></CommandItem></CommandList></Command></DemoPopoverContent></Popover.Root></div>
 </article>
}
